URL_SIRENE4_EXTRACTION = "s3://projet-ape/extractions/20240812_sirene4.parquet"
URL_SIRENE4_MULTIVOCAL = "s3://projet-ape/NAF-revision/relabeled-data"
URL_MAPPING_TABLE = "s3://projet-ape/NAF-revision/table-correspondance-naf2025.xls"
URL_EXPLANATORY_NOTES = "s3://projet-ape/NAF-revision/notes-explicatives-naf2025.xlsx"
URL_GROUND_TRUTH = "s3://projet-ape/label-studio/annotation-campaign-2024/rev-NAF2025/preprocessed/training_data_NAF2025.parquet"
